Django/school_program/Dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

Django/school_program/school_program/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import include

urlpatterns = [
    path('', include('Dashboard.urls')),
    path('admin/', admin.site.urls),
    path('', include('students.urls')),
    path('', include('schools.urls')),
    path('', include('subjects.urls')),
    
]

Django/school_program/schools/urls.py
from django.urls import path
from . import views

app_name='schools'

urlpatterns = [
    path('schools/', views.schoolIndex, name='school_index'),
    path('schools/<int:pk>/', views.school_detail, name='school_detail'),
    path('schools/add/', views.add, name="add")
    
]

Django/school_program/students/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name='students'




urlpatterns = [
    #url('', views.index, name='index'),
    path('students/', views.index, name='students'),
    path('students/<int:pk>/', views.student_detail, name='student_detail'),
    path('students/add/', views.add, name="add")
]

Django/school_program/subjects/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name='subjects'


urlpatterns = [
    #url('', views.index, name='index'),
    path('subjects/', views.index, name='index'),
    path('subjects/<int:subject_id>/', views.subject_index, name= 'detail'),
    path('subjects/add/', views.add, name="add")
]

Django/school_program/schools/models.py
from django.db import models

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    no_of_students = models.IntegerField()
    
    class Meta:
        db_table = 'tbl_school'
        managed = True #flush or sync db
        
    def __str__(self):
        return self.name

Django/school_program/students/models.py
from django.db import models
from schools.models import School


    
 # Create your models here.
class Student(models.Model):    
    name = models.CharField(max_length=100)
    registration_number = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    age = models.IntegerField()
    school = models.ForeignKey(School,on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'tbl_student'
        managed = True #flush or sync db
            
    def __str__(self):
        return self.name

Django/school_program/subjects/models.py
from django.db import models
from students.models import Student
from .grading_system import gradingSystem

# Create your models here.
class Subject(models.Model):
    subject_name = models.CharField(max_length=10)
    score = models.CharField(max_length=10)
    student = models.ForeignKey(Student, on_delete=models.CASCADE,default=1)
   
    
    class Meta:
        db_table = 'tbl_subject'
        managed = True #flush or sync db
            
    def __str__(self):
        return self.subject_name
    
    def ShowGrade(self):
        return gradingSystem(self.score)
    
    def __str__(self):
        return '{} {}' .fomart(self.name, self.showgrade())

Django/school_program/Dashboard/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'dashboard/dashboard.html',{})

Django/school_program/schools/views.py
from django.shortcuts import render,redirect
from .models import School
from students.models import Student
# from subjects.models import 

# Create your views here.
def schoolIndex(request):
    schools=School.objects.all()
    context={'schools': schools}
    return render(request,'schools/schools_list.html', context)

def school_detail(request, pk):
    #select * from schools where school_id=x
    school = School.objects.get(pk=pk)
    #select * from students where school_id=x
    students = Student.objects.filter(pk=pk)
    context= {
        'school':school, 
        'students':students,
        # 'subjects':subjects,
    }
    return render(request,'schools/detail.html', context) 


def add(request):
    if request.method =="POST":
        form =request.POST
        #print(form)
        school= School()
        school.code = form['code']
        school.name = form['name']
        school.address = form['address']
        school.no_of_students = form['no_of_students']
        school.save()   #insert in database
        
        #give us a new id of the recorded item
        return redirect('schools:school_detail', school.pk)
    return render(request, 'schools/add.html', {})

Django/school_program/students/views.py
from django.shortcuts import render
from .models import Student
from schools.models import School
from subjects.models import Subject

# Create your views here.
def index(request):
    student_details = Student.objects.all()
    context = {'student_data': student_details}
    return render(request, 'students/students_lists.html', context)

def student_detail(request, pk):
    #select * from students where student-id=x
    student = Student.objects.get(pk=pk)
    #select * from subjects where student_id=x
    subjects = Subject.objects.filter(pk=pk)
    
    context={'student': student, 'subjects':subjects}
    return render(request,'students/detail.html', context)

def add(request):
    if request.method =="POST":
        form =request.POST
        print(form)
        student= Student()
        student.name = form['code']
        student.registration_number = form['name']
        student.address = form['address']
        student.age = form['age']
        student.school = School.objects.get(pk=form['school'])
        student.save()   #insert in database 
               
        #give us a new id of the recorded item (use the appname and the viewnametag)
        return redirect ('student:student_list', student.pk)
    
    schools=School.objects.all()
    context={'schools':schools}
    
    
    return render(request, 'students/add.html', context)

Django/school_program/subjects/views.py
from django.shortcuts import render
from .models import Subject
from students.models import Student


# Create your views here.
def index(request):
    subjects = Subject.objects.all()
    context = {'subjects':subjects}
    return render(request, 'subjects/subject_lists.html', context)

def subject_index(request,pk):
    school_subjects = Subject.objects.get(pk=pk)  
    context = {'school_subjects': school_subjects}
    return render(request,"subjects/subject_details.html",context)

def add(request):
    if request.method =="POST":
        form =request.POST
       # print(form)
        subject= Subject()
        subject.subject_name = form['subject_name']
        subject.score = form['score']
        subject.student = Student.objects.get(pk=form['student'])   #foreign key
        subject.save()   #insert in database       
        #give us a new id of the recorded item
        return redirect('subject:index') #redirect to the link under urls.py

    students = Student.objects.all()  #gives options of the students
    context={'students':students}
       
    return render(request, 'subjects/add.html', context)

Django/school_program/Dashboard/templates/dashboard/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
</head>
<body>
    <h2>Dashboard</h2>

    <ul>
        <li> <a href="/schools">Schools</a> </li>
        <li><a href="/students">Students</a></li>
        <li><a href="/subjects">Subjects</a></li>
    </ul>
</body>
</html>

Django/school_program/subjects/templates/subjects/add.html
<!-- creating form that adds a subject -->
<!DOCTYPE html>
<html lang='eng'>
    <head>
        <meta charset= "UTF-8" >
        <title> Add subject</title>
    </head>
    <body>
        <h2>Add new subject</h2>

        <form action="{% url 'subjects:add'%}" method="post" name="frmSubjects">
            {%csrf_token %}

            <label for="subject_name">subject_name: </label>
            <input id="subject_name" type="text" name="subject_name" values="">
            <br>
            <br>
            <label for="score"> score: </label>
            <input id="score" type="text" name="score" values="">
            <br>
            <br>
            <label for="student">student: </label>
            <select name="student" id="">
            <option value="">Select a student</option>
            {% for student in students %}
                <option value="{{ student.id }}">{{ student.name }}</option>
            {% endfor %}
        
            <input type ="submit" value="save">

        </form>
    </body>

</html>

Django/school_program/subjects/templates/subjects/subject_details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subject</title>
</head>

<body>
    <h2>Subjects for : {% for studentname in student_name%}
        {{studentname.name}}
        {% endfor %}
    </h2>
    <table>
        <tr>
            <th>Name</th>
            <th>Score</th>
            <th>Grade</th>

        </tr>
        {% for subject in all_student_subjects%}
        <tr>
            <td>{{subject.name}}</td>
            <td>{{subject.score}}</td>
            <td>{{subject.ShowGrade}}</td>

            {% endfor %}
        </tr>
    </table>
    <p><a href="{% url 'students' %}">Home</a></p>
</body>

</html>

Django/school_program/subjects/templates/subjects/subject_lists.html
<!DOCTYPE html>
<html lang="en">
<head>
<title> List of subjects </title>
</head>
<body>
   <h1>subjects lists</h1>
   <table>
       <thead>
           <th>
                ID
            </th>
            <th>
                Name
            </th>
            <th>
                 Score
            </th>
            <th>
                student
            </th>
       </thead>
       <tbody>
   {% for subject in subjects %}
   <tr>
    <td>
        <a href="% url 'subject_detail' subject.id %}">{{ subject.id }}</a>
        </td>
       <td>
       {{ subject.subject_name}}
       </td>
       <td>
           {{ subject.score}}
       </td>
       <td>
        {{ subject.student}}
    </td>
   </tr>
   <p></p>
   {% endfor %}
       </tbody>
   </table>
   <p><a href="{%url 'index' %}">Home</a></p>
</body>
</html>