Django/banking_app/banking_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('currency.urls')),
    path('', include('customer.urls')),
    path('', include('transactions.urls')),
    path('', include('users.urls')),
    path('', include('staff.urls')),
]

Django/banking_app/staff/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name= 'staff'

urlpatterns = [
    # path('staff/', views.index, name='index'),
    path('login/', views.staffLogin, name='s_Login'),
    path('menu',views.menu_section,name='menu_section'),
]

Django/banking_app/transactions/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name= 'transactions'

urlpatterns = [
    path('send/<int:pk>', views.Send_index, name='send_index'),
    path('withdraw/<int:pk>', views.withdrawal_index, name='withdrawal_index'),
    path('do_deposit/<int:pk>', views.Deposit_index, name='deposit_index'),
    path('#',views.CustomerLogin,name='customerlogin'),
    path('profile/<int:pk>',views.customerProfile,name='customer_profile'),
    path('w_report/<int:pk>', views.wReport, name='wReport'),
    path('s_report/<int:pk>', views.sReport, name='sReport'),
    path('d_report/<int:pk>', views.dReport, name='dReport'),
    

]

Django/banking_app/transactions/models.py
from django.db import models
from account.models import Account
from account.models import Customer
from django.utils import timezone

# Create your models here.
class T_type(models.Model):
    tName = models.CharField(max_length=10)
    tCode = models.IntegerField()
    
    
    class Meta:
        db_table = 'transcType'
        managed = True #flush or sync db
        
    def __str__(self):
        return self.tName
    
# class All_transactions(models.Model): 
#     time = models.DateTimeField(default=timezone.now)
#     trans_code= models.IntegerField()
#     amount= models.FloatField()
#     balance= models.FloatField()
#     customer = models.ForeignKey(Customer,on_delete=models.CASCADE,default=1)
    
    class Meta:
        db_table = 'transactions'
        managed = True #flush or sync db
        
    def __str__(self):
        return self.trans_type

class SendMoney(models.Model):
    time = models.DateTimeField(default=timezone.now)
    trans_code= models.IntegerField()
    mobile = models.CharField(max_length=15)
    amount = models.IntegerField()
    balance= models.FloatField()
    AccNo = models.ForeignKey(Account,on_delete=models.CASCADE,default=1)
    
    
    class Meta:
        db_table = 'sendMoney'
        managed = True #flush or sync db
        
    def __str__(self):
        return self.name
    
class Withdrawal(models.Model):
    time = models.DateTimeField(default=timezone.now)
    trans_code= models.IntegerField()
    amount = models.IntegerField()
    balance= models.FloatField()
    AccNo = models.ForeignKey(Account,on_delete=models.CASCADE,default=1)
    
    class Meta:
        db_table = 'withdraw'
        managed = True #flush or sync db
        
    def __str__(self):
        return self.amount
    
class Deposit(models.Model):
    time = models.DateTimeField(default=timezone.now)
    trans_code= 2
    amount = models.IntegerField()
    balance= models.FloatField()
    AccNo = models.ForeignKey(Account,on_delete=models.CASCADE,default=1)
    
    class Meta:
        db_table = 'deposit'
        managed = True #flush or sync db
    
    def __str__(self):
        return self.amount

Django/banking_app/transactions/forms.py
from .models import Customer
from django.contrib.auth.forms import UserCreationForm
#import form class from django
from django import forms
#import customer model
from django.contrib.auth.models import User
#create formclass for customer

class CustomerForm(forms.ModelForm):
    #create a meta class
    class Meta:
        model = Customer
        fields = "__all__" #can also use exclude = ['name'] to exclude fields

class CreateUserForm(UserCreationForm):
    
    #meta class
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

Django/banking_app/transactions/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from account.models import Account
from account.models import Customer
from .models import SendMoney
from .models import Withdrawal
from .models import Deposit
# from .models import All_transactions
from .models import T_type


# Create your views here.
def Send_index(request, pk):
    account = Account.objects.get(pk=pk)
    current_balance = account.balance 
    
    if request.method =="POST":
        form = request.POST
        send = SendMoney()
        send.mobile = float(form['mobile'])
        send.amount = float(form['amount'])
        send.AccNo = float(form['AccNo'])
        if current_balance < withdrawal.amount:
            messages.info(request,'Request failed! your balance of {} is not suficient to complete this transaction'.format(current_balance))
            
        else:
            print(send.amount,send.AccNo) 
            new_balance = current_balance - send.amount
            account.balance = new_balance
            account.save()
            send.save()
            
            messages.success(request,'Confirmed! Ksh {} was sent to {} your new balance is {}'.format(send.amount, send.AccNo, new_balance))

        
    customer = Customer.objects.get(pk=pk)
    context ={
        'customer':customer
    }
    
    return render(request, 'transactions/sendMoney.html', context)


        
def withdrawal_index(request,pk):
    account = Account.objects.get(pk=pk)
    current_balance = account.balance 
    
    if request.method =="POST":
        form = request.POST
        withdrawal = Withdrawal()
        withdrawal.amount = float(form['amount'])
        if current_balance < withdrawal.amount:
            messages.info(request,'Transaction failed! You cannot withdraw an amount that is greater than your balance of {}'.format(current_balance))
            
        else:
            print(withdrawal.amount,withdrawal.AccNo) 
            new_balance = current_balance - withdrawal.amount
            account.balance = new_balance
            account.save()
            withdrawal.save()
            
            messages.success(request,'Transaction sucessful. you made awithdrawal of {}. your new balance is {}'.format(withdrawal.amount, new_balance))

        
    customer = Customer.objects.get(pk=pk)
    context ={
        'customer':customer
    }
    return render(request, 'transactions/withdraw.html',context)

   
def Deposit_index(request,pk):
   
    account = Account.objects.get(pk=pk)
    current_balance = account.balance 
    
    if request.method =="POST":
        form = request.POST
        deposit = Deposit()
        deposit.amount = float(form['amount'])
        
        new_balance = current_balance + deposit.amount
        account.balance = new_balance
        account.save()
        deposit.save()
        
        messages.success(request,'Transaction sucessful. You have made a deposit of {}. your new balance is {}'.format(deposit.amount, new_balance))
        
        customer = Customer.objects.get(pk=pk)
        return redirect('transactions:deposit_index',customer.pk)
    
    customer = Customer.objects.get(pk=pk)
    context ={
        'customer':customer
    }
    return render(request, 'transactions/loadMoney.html',context)
        
        

def customerProfile(request,pk):
    customer = Customer.objects.get(pk=pk)
    account = Account.objects.get(pk=pk)
    context = {
            'customer': customer,
            'account':account
    }
    return render(request, "transactions/customer_profile.html",context)


def CustomerLogin(request):
   
    if request.method == "POST":
        form = request.POST
        mobileN = form['mobile']
        pin = form['pin']
        print(mobileN)
        print(pin)
        customer_info = Customer.objects.get(mobile=mobileN)
        print(customer_info)
        print(customer_info.mobile)
        print(customer_info.pin)
        if customer_info is not None:
            print('Customer info is not empty')
            if customer_info.pin == pin:
                print('Pin Matched redirect')
                return redirect('transactions:customer_profile',customer_info.pk)
            else:
                print('Pin NOT Matched ')
                messages.info(request,'Invalid Phone or Pin')
        else:
            print('Customer info is none')
            messages.info(request,'Invalid Phone or Pin')
            
    context = {}
    return render(request,"transactions/customer_login.html",context)

def wReport(request, pk): 

    customer = Customer.objects.get(pk=pk)
    account = Account.objects.get(pk=pk)
    withdrawals = Withdrawal.objects.filter(pk=pk)
     
    context ={
        'withdrawals':withdrawals,
        'account':account,
        'customer':customer,
    }
    return render(request, "transactions/withdrawReport.html",context)
    
def sReport(request, pk):
    
    customer = Customer.objects.get(pk=pk)
    account = Account.objects.get(pk=pk)
    debit = SendMoney.objects.filter(pk=pk)

    context ={
        'debit':SendMoney,
        'account':account,
        'customer':customer,
    }    
    return render(request, "transactions/sReport.html", context)


def dReport(request, pk):
    customer = Customer.objects.get(pk=pk)
    account = Account.objects.get(pk=pk)
    credit = Deposit.objects.filter(pk=pk)


    context ={
        'credit':Deposit,
        'account':account,
        'customer':customer,
    }      
    return render(request, "transactions/dReport.html", context)

Django/banking_app/transactions/templates/transactions/customer_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Login</title>
    <style>
        .login-box
		{
			height: 50%;
			width: 30%;
			border: 1px grey;
			margin-left: 35%;
			margin-top: 10%;
			position: relative;
      		box-shadow: 21px 12px 24px 10px rgba(0, 0, 0, .5);
      		background: #dadada;
		}
		.login-header
		{
			text-align: center;
			font-family: "vardhana",cursive;
			font-size: 35px;
			background: linear-gradient(to bottom, #3f5b64 0%, #d26edb 100%);
			color:rgb(228, 139, 139);
			position: relative;
      		box-shadow: 1px 3px 14px  rgba(65, 55, 55, 0.5);
		}
		.login-body
		{
			padding: 20px;
			line-height: 2;
		}

    </style>
</head>
<body>

    <div class="login-box">
        <div class="login-header">Login</div>
        <div class="login-body">
            <form action="{% url 'transactions:customerlogin' %}" name="frmstusent" method="POST">
                {% csrf_token %}
                <!--Prevents cross site scripting-->
                <label>Mobile Number</label>
                <input type="text" id="Mobile" name="mobile" value="">
                <br/>
                <label>Pin</label>
                <input type="text" id="Pin" name="pin" value="">
                
                <input type="submit" value="Login" class="form-control btn btn-success " name="">
                {% for message in messages %}
                {{message}}
                {% endfor %}
                <br>
                <br>
                <p style="text-align:centre"><a href=" {% url 'staff:s_Login' %} "> Staff Login? </a></p>
                    
            </form>
        </div>
</div>

</body>

Django/banking_app/transactions/templates/transactions/customer_profile.html
{% extends 'base/container_page.html' %}

{% block content%}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Customer details</h1>
      </div>
      

        <p>Customer Name: {{ customer.name }}</p> 
        <p>Mobile Number: {{ customer.mobile }}</p>
        <p>Account Number: {{ account.AccNo }}</p>
        <p>Account Balance : {{ account.balance }}</p>
{% endblock %}

Django/banking_app/transactions/templates/transactions/dReport.html
{% extends 'base/container_page.html' %}
{%block content %} 

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h2 class="h2">Money Transfer Report</h2>
      </div>
<head>
    <style>
        .main {
            padding: 40px 0;
        }

        .main input,
        .main input::-webkit-input-placeholder {
            font-size: 11px;
            padding-top: 3px;
        }

        .main-center {
            margin-top: 30px;
            margin: 0 auto;
            max-width: 1000px;
            padding: 10px 40px;
            background: #b1dbeb;
            color: #FFF;
            text-shadow: none;
            -webkit-box-shadow: 0px 3px 5px 0px rgba(0, 0, 0, 0.31);
            -moz-box-shadow: 0px 3px 5px 0px rgba(0, 0, 0, 0.31);
            box-shadow: 0px 3px 5px 0px rgba(0, 0, 0, 0.31);

        }

        span.input-group-addon i {
            color: #56a56a80;
            font-size: 17px;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="main">
            <div class="main-center">

                <table class="table">
                    
                    <thead>
                        <tr>
                            <th scope="col">Mobile Number</th>
                            <th scope="col">Credit</th>
                            <th scope="col">Account Number</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for credit in credits %}
                        <tr>
                            <td>{{ credit.mobile }}</td>
                            <td>{{ credit.amount }}</td>
                            <td>{{ credit.AccNo }}</td>
                           
                        </tr>
                        {% endfor %}
                    </tbody>
            </div>
            <!--main-center"-->
        </div>
        <!--main-->
    </div>



{% endblock %}

Django/banking_app/transactions/templates/transactions/loadMoney.html
<!-- #creating a form that sends money to another recepient -->
{% extends 'base/container_page.html' %}
{%block content %} 

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Deposit</h1>
      </div>

      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}

        <form action="{% url 'transactions:deposit_index' customer.id %}" method="post" name="frmloadMoney">
            {%csrf_token %}
            <label for="amount">Amount: </label>
            <input id="amount" type="text" name="amount" values="">
            
            <input type ="submit" value="save">

        </form>

{% endblock %} 

Django/banking_app/transactions/templates/transactions/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #7abecc !important;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;

        }

        .login_btn {
            width: 100%;
            background: #b5e72b !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
    </style>

</head>

<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">


                    <h3 id="form-title">LOGIN</h3>
                </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" name="username" placeholder="Username..." class="form-control">
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" name="password" placeholder="Password..." class="form-control">
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Login">
                        </div>
                    </form>

                </div>

                <div class="mt-4">
                    {% for message in messages%}
                    <p id="messages">{{message}}</p>
                    {% endfor %}
                    <div class="d-flex justify-content-center links">
                        Don't have an account? <a href="{% url 'customer:register'%}" class="ml-2">Sign Up</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>

</html>

Django/banking_app/transactions/templates/transactions/register.html
<!DOCTYPE html>
<html>

<head>
    <title>Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #7abecc !important;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #015c4b;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;
        }

        .login_btn {
            width: 100%;
            background: #234d5c !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }
    </style>

</head>

<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">
                    <h3 id="form-title">REGISTER ACCOUNT</h3>
                </div>
                <div class="d-flex justify-content-center form_container">

                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            {{form.username}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                            </div>
                            {{form.email}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{form.password1}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{form.password2}}
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Register Account">
                        </div>
                    </form>
                    
                </div>
                {{form.errors}}
                <div class="mt-4">
                    {% for message in messages%}
                    <p id="messages">{{message}}</p>
                    {% endfor %}
                    <div class="d-flex justify-content-center links">
                        Already have an account? <a href="{% url 'customer:login' %}" class="ml-2">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field 
*/

        //Query All input fields
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder = 'Username..';
        form_fields[2].placeholder = 'Email..';
        form_fields[3].placeholder = 'Enter password...';
        form_fields[4].placeholder = 'Re-enter Password...';


        for (var field in form_fields) {
            form_fields[field].className += ' form-control'
        }
    </script>
</body>

</html>

Django/banking_app/transactions/templates/transactions/sReport.html
{% extends 'base/container_page.html' %}
{%block content %} 

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h2 class="h2">Money Transfer Report</h2>
      </div>
<head>
    <style>
        .main {
            padding: 40px 0;
        }

        .main input,
        .main input::-webkit-input-placeholder {
            font-size: 11px;
            padding-top: 3px;
        }

        .main-center {
            margin-top: 30px;
            margin: 0 auto;
            max-width: 1000px;
            padding: 10px 40px;
            background: #b1dbeb;
            color: #FFF;
            text-shadow: none;
            -webkit-box-shadow: 0px 3px 5px 0px rgba(0, 0, 0, 0.31);
            -moz-box-shadow: 0px 3px 5px 0px rgba(0, 0, 0, 0.31);
            box-shadow: 0px 3px 5px 0px rgba(0, 0, 0, 0.31);

        }

        span.input-group-addon i {
            color: #56a56a80;
            font-size: 17px;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="main">
            <div class="main-center">

                <table class="table">
                    
                    <thead>
                        <tr>
                            <th scope="col">Mobile Number</th>
                            <th scope="col">Debit</th>
                            <th scope="col">Account Number</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for debit in debits %}
                        <tr>
                            <td>{{ debit.mobile }}</td>
                            <td>{{ debit.amount }}</td>
                            <td>{{ debit.AccNo }}</td>
                           
                        </tr>
                        {% endfor %}
                    </tbody>
            </div>
            <!--main-center"-->
        </div>
        <!--main-->
    </div>



{% endblock %}

Django/banking_app/transactions/templates/transactions/sendMoney.html
<!-- #creating a form that sends money to another recepient -->

{% extends 'base/container_page.html' %}
{%block content %} 

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Send money</h1>
      </div>
      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}

        <form action="{% url 'transactions:send_index' customer.id %}" method="post" name="frmSendMoney">
            {%csrf_token %}

            <label for="mobile">Mobile: </label>
            <input id="mobile" type="text" name="mobile" values="">
            <br>
            <br>
            <label for="amount">Amount: </label>
            <input id="amount" type="number" name="amount" values="">
            <br>
            <br>
            <label for="AccNo">Account number: </label>
            <input id="AccNo" type="number" name="AccNo" values="">
            <br>
            <label>Customer Id</label>

            <input name="customer_id" value="{{customer_id}}" type="text" />
            <br>
            <input type ="submit" value="save">

        </form>
{% endblock %} 

Django/banking_app/transactions/templates/transactions/withdraw.html
<!-- #creating a form that sends money to another recepient -->
{% extends 'base/container_page.html' %}
{%block content %} 

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Withdraw</h1>
      </div>
      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}

    

        <form action="{% url 'transactions:withdrawal_index' customer.id %}" method="post" name="frmwithdrawMoney">
            {%csrf_token %}

            <label for="amount">Amount: </label>
            <input id="amount" type="number" name="amount" values="">
            <br>
            <br>
            <input type ="submit" value="save">

        </form>
    
{% endblock %}